import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const supportedEnvs = new Set(['local', 'prod']);
const requestedEnv = process.argv[2] ?? process.env.APP_ENV ?? 'local';

if (!supportedEnvs.has(requestedEnv)) {
  throw new Error(`[sync-env] Unsupported APP_ENV "${requestedEnv}". Use one of: ${[...supportedEnvs].join(', ')}`);
}

const projectRoot = process.cwd();
const envFilePath = resolve(projectRoot, `.env.${requestedEnv}`);
const exampleFilePath = resolve(projectRoot, '.env.example');
const sourceFilePath = existsSync(envFilePath) ? envFilePath : exampleFilePath;
const jsTargetFilePath = resolve(projectRoot, 'src/shared/config/generatedEnv.ts');
const androidTargetFilePath = resolve(projectRoot, 'android/app/env.generated.gradle');
const iosTemplateFilePath = resolve(projectRoot, 'ios/Pawever/Info.plist');
const iosTargetFilePath = resolve(projectRoot, 'ios/Pawever/Info.generated.plist');

const parseEnv = raw => {
  return raw
    .split(/\r?\n/)
    .map(line => line.trim())
    .filter(line => line.length > 0 && !line.startsWith('#'))
    .reduce((acc, line) => {
      const separatorIndex = line.indexOf('=');

      if (separatorIndex === -1) {
        return acc;
      }

      const key = line.slice(0, separatorIndex).trim();
      const value = line.slice(separatorIndex + 1).trim().replace(/^['"]|['"]$/g, '');

      if (key.length > 0) {
        acc[key] = value;
      }

      return acc;
    }, {});
};

const sourceRaw = readFileSync(sourceFilePath, 'utf8');
const env = parseEnv(sourceRaw);

const requiredKeys = ['API_BASE_URL', 'WEB_BASE_URL', 'PRIVACY_POLICY_URL', 'SUPPORT_EMAIL'];
const optionalKeys = ['KAKAO_NATIVE_APP_KEY', 'NAVER_CLIENT_ID', 'NAVER_CLIENT_SECRET', 'NAVER_IOS_URL_SCHEME'];

requiredKeys.forEach(key => {
  if (!env[key]) {
    throw new Error(`[sync-env] Missing "${key}" in ${sourceFilePath}`);
  }
});

if (!env.KAKAO_NATIVE_APP_KEY && env.KAKAO_REST_API_KEY) {
  throw new Error(
    `[sync-env] Found "KAKAO_REST_API_KEY" in ${sourceFilePath}, but the current React Native Kakao login flow requires "KAKAO_NATIVE_APP_KEY". Replace it with the Native App Key from Kakao Developers.`,
  );
}

if (env.NAVER_REDIRECT_URI) {
  console.warn(
    `[sync-env] "NAVER_REDIRECT_URI" is present in ${sourceFilePath}, but the current mobile SDK flow does not read this value. It will not be generated into app config.`,
  );
}

env.APP_ENV = requestedEnv;
optionalKeys.forEach(key => {
  env[key] = env[key] ?? '';
});

const fileContent = `// This file is generated by scripts/sync-env.mjs. Do not edit by hand.
export const generatedEnv = Object.freeze({
  APP_ENV: ${JSON.stringify(env.APP_ENV)},
  API_BASE_URL: ${JSON.stringify(env.API_BASE_URL)},
  WEB_BASE_URL: ${JSON.stringify(env.WEB_BASE_URL)},
  PRIVACY_POLICY_URL: ${JSON.stringify(env.PRIVACY_POLICY_URL)},
  SUPPORT_EMAIL: ${JSON.stringify(env.SUPPORT_EMAIL)},
  KAKAO_NATIVE_APP_KEY: ${JSON.stringify(env.KAKAO_NATIVE_APP_KEY)},
  NAVER_CLIENT_ID: ${JSON.stringify(env.NAVER_CLIENT_ID)},
  NAVER_CLIENT_SECRET: ${JSON.stringify(env.NAVER_CLIENT_SECRET)},
  NAVER_IOS_URL_SCHEME: ${JSON.stringify(env.NAVER_IOS_URL_SCHEME)},
});

export type GeneratedEnv = typeof generatedEnv;
`;

const kakaoUrlScheme = env.KAKAO_NATIVE_APP_KEY ? `kakao${env.KAKAO_NATIVE_APP_KEY}` : '';

const androidFileContent = `// This file is generated by scripts/sync-env.mjs. Do not edit by hand.
ext.paweverNativeEnv = [
  kakaoAppKey: ${JSON.stringify(env.KAKAO_NATIVE_APP_KEY)},
  kakaoScheme: ${JSON.stringify(kakaoUrlScheme)},
]
`;

const iosTemplate = readFileSync(iosTemplateFilePath, 'utf8');
const iosFileContent = iosTemplate
  .replaceAll('__KAKAO_APP_KEY__', env.KAKAO_NATIVE_APP_KEY)
  .replaceAll('__KAKAO_URL_SCHEME__', kakaoUrlScheme)
  .replaceAll('__NAVER_IOS_URL_SCHEME__', env.NAVER_IOS_URL_SCHEME);

mkdirSync(dirname(jsTargetFilePath), { recursive: true });
mkdirSync(dirname(androidTargetFilePath), { recursive: true });
mkdirSync(dirname(iosTargetFilePath), { recursive: true });

writeFileSync(jsTargetFilePath, fileContent);
writeFileSync(androidTargetFilePath, androidFileContent);
writeFileSync(iosTargetFilePath, iosFileContent);

console.log(`[sync-env] Wrote ${jsTargetFilePath}, ${androidTargetFilePath}, ${iosTargetFilePath} from ${sourceFilePath}`);
