import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const supportedEnvs = new Set(['local', 'prod']);
const requestedEnv = process.argv[2] ?? process.env.APP_ENV ?? 'local';

if (!supportedEnvs.has(requestedEnv)) {
  throw new Error(`[sync-env] Unsupported APP_ENV "${requestedEnv}". Use one of: ${[...supportedEnvs].join(', ')}`);
}

const projectRoot = process.cwd();
const envFilePath = resolve(projectRoot, `.env.${requestedEnv}`);
const exampleFilePath = resolve(projectRoot, '.env.example');
const sourceFilePath = existsSync(envFilePath) ? envFilePath : exampleFilePath;
const targetFilePath = resolve(projectRoot, 'src/shared/config/generatedEnv.ts');

const parseEnv = raw => {
  return raw
    .split(/\r?\n/)
    .map(line => line.trim())
    .filter(line => line.length > 0 && !line.startsWith('#'))
    .reduce((acc, line) => {
      const separatorIndex = line.indexOf('=');

      if (separatorIndex === -1) {
        return acc;
      }

      const key = line.slice(0, separatorIndex).trim();
      const value = line.slice(separatorIndex + 1).trim().replace(/^['"]|['"]$/g, '');

      if (key.length > 0) {
        acc[key] = value;
      }

      return acc;
    }, {});
};

const sourceRaw = readFileSync(sourceFilePath, 'utf8');
const env = parseEnv(sourceRaw);

const requiredKeys = ['API_BASE_URL', 'WEB_BASE_URL', 'PRIVACY_POLICY_URL', 'SUPPORT_EMAIL'];

requiredKeys.forEach(key => {
  if (!env[key]) {
    throw new Error(`[sync-env] Missing "${key}" in ${sourceFilePath}`);
  }
});

env.APP_ENV = requestedEnv;

const fileContent = `// This file is generated by scripts/sync-env.mjs. Do not edit by hand.
export const generatedEnv = Object.freeze({
  APP_ENV: ${JSON.stringify(env.APP_ENV)},
  API_BASE_URL: ${JSON.stringify(env.API_BASE_URL)},
  WEB_BASE_URL: ${JSON.stringify(env.WEB_BASE_URL)},
  PRIVACY_POLICY_URL: ${JSON.stringify(env.PRIVACY_POLICY_URL)},
  SUPPORT_EMAIL: ${JSON.stringify(env.SUPPORT_EMAIL)},
});

export type GeneratedEnv = typeof generatedEnv;
`;

mkdirSync(dirname(targetFilePath), { recursive: true });
writeFileSync(targetFilePath, fileContent);

console.log(`[sync-env] Wrote ${targetFilePath} from ${sourceFilePath}`);
